<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>project_status</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="PROJECT_STATUS_files/libs/clipboard/clipboard.min.js"></script>
<script src="PROJECT_STATUS_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="PROJECT_STATUS_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="PROJECT_STATUS_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="PROJECT_STATUS_files/libs/quarto-html/popper.min.js"></script>
<script src="PROJECT_STATUS_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PROJECT_STATUS_files/libs/quarto-html/anchor.min.js"></script>
<link href="PROJECT_STATUS_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PROJECT_STATUS_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PROJECT_STATUS_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PROJECT_STATUS_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PROJECT_STATUS_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="cml-final-project---progress-tracker" class="level1">
<h1>CML Final Project - Progress Tracker</h1>
<p><strong>Student:</strong> [Your Name]<br>
<strong>Project:</strong> MIMIC-III ICU Predictions<br>
<strong>Tasks:</strong> Hospital Expire Flag (Classification) + Length of Stay (Regression)</p>
<hr>
<section id="current-best-scores" class="level2">
<h2 class="anchored" data-anchor-id="current-best-scores">📊 Current Best Scores</h2>
<section id="classification-hef---hospital-expire-flag" class="level3">
<h3 class="anchored" data-anchor-id="classification-hef---hospital-expire-flag">Classification (HEF - Hospital Expire Flag)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 39%">
<col style="width: 18%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Public Score</th>
<th>Date</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Gradient Boosting</strong></td>
<td><strong>0.727226</strong></td>
<td>2024-11-19</td>
<td>🏆 Best classification score</td>
</tr>
<tr class="even">
<td>Ensemble</td>
<td>0.721090</td>
<td>2024-11-19</td>
<td>Weighted average of models</td>
</tr>
<tr class="odd">
<td>XGBoost</td>
<td>0.715164</td>
<td>2024-11-19</td>
<td>Underperformed vs GB</td>
</tr>
<tr class="even">
<td>Extra Trees</td>
<td>0.688217</td>
<td>2024-11-19</td>
<td>Lowest score</td>
</tr>
</tbody>
</table>
<p><strong>Metric:</strong> ROC-AUC (higher is better)<br>
<strong>Target:</strong> Beat baseline, maximize AUC</p>
</section>
<section id="regression-los---length-of-stay" class="level3">
<h3 class="anchored" data-anchor-id="regression-los---length-of-stay">Regression (LOS - Length of Stay)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 39%">
<col style="width: 18%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Public Score</th>
<th>Date</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>GB Enhanced v2</strong></td>
<td><strong>20.751931</strong></td>
<td>2024-11-19</td>
<td>🏆 Best - with diagnosis features</td>
</tr>
<tr class="even">
<td>Ensemble Weighted</td>
<td>~20.8</td>
<td>2024-11-19</td>
<td>GB+RF+ET ensemble</td>
</tr>
<tr class="odd">
<td>Ensemble Average</td>
<td>~20.8</td>
<td>2024-11-19</td>
<td>Simple average</td>
</tr>
<tr class="even">
<td>GB Diagnosis Only</td>
<td>21.021833</td>
<td>2024-11-19</td>
<td>Diagnosis features only</td>
</tr>
<tr class="odd">
<td>XGBoost</td>
<td>~21.0</td>
<td>2024-11-19</td>
<td>Slight regression</td>
</tr>
<tr class="even">
<td>Gradient Boosting</td>
<td>21.309904</td>
<td>2024-11-19</td>
<td>Original baseline</td>
</tr>
<tr class="odd">
<td>Log-transform ensemble</td>
<td>TBD</td>
<td>-</td>
<td>Worse on validation</td>
</tr>
</tbody>
</table>
<p><strong>Metric:</strong> Unknown (professor won’t tell us - likely RMSE or MSE) <strong>Target:</strong> Beat 15.7 (NN “demanding” benchmark) <strong>Gap:</strong> Currently ~5 points behind benchmark</p>
<hr>
</section>
</section>
<section id="development-log" class="level2">
<h2 class="anchored" data-anchor-id="development-log">📅 Development Log</h2>
<section id="initial-setup-classification" class="level3">
<h3 class="anchored" data-anchor-id="initial-setup-classification">2024-11-19 - Initial Setup &amp; Classification</h3>
<p><strong>Completed:</strong> - ✅ Project organization (scripts/classification vs regression folders) - ✅ Data exploration and preprocessing pipeline - ✅ Feature engineering (medical features: shock index, pulse pressure, etc.) - ✅ Classification baseline models (RF, GB, ET, Ensemble) - ✅ Discovered GB performs best (0.727 AUC) - ✅ Fixed submission format (probabilities vs binary, added icustay_id) - ✅ Tried XGBoost and Stacking - didn’t improve over GB</p>
<p><strong>Key Learnings:</strong> - Gradient Boosting consistently outperforms other tree methods - Feature engineering didn’t help classification (kept it simple) - Ensemble didn’t beat single GB model - XGBoost underperformed (0.715 vs 0.727)</p>
<p><strong>Files Created:</strong> - <code>scripts/classification/quickstart_submission.py</code> - <code>scripts/classification/generate_kaggle_submissions.py</code> - <code>scripts/classification/finetune_gb.py</code> - <code>scripts/classification/xgboost_sub.py</code> - <code>scripts/classification/stacking_sub.py</code></p>
</section>
<section id="regression-los-initial-attempts" class="level3">
<h3 class="anchored" data-anchor-id="regression-los-initial-attempts">2024-11-19 - Regression (LOS) Initial Attempts</h3>
<p><strong>Completed:</strong> - ✅ Adapted classification pipeline for regression - ✅ Created <code>los_prep.py</code> module (similar to classification prep) - ✅ Generated initial submissions (RF, GB, ET, Ensemble) - ✅ GB achieved 21.3 RMSE (best so far) - ✅ Identified benchmark: NN at 15.7 RMSE</p>
<p><strong>Files Created:</strong> - <code>scripts/regression/los_prep.py</code> - <code>scripts/regression/quickstart_los.py</code> - <code>scripts/regression/generate_los_submissions.py</code> - <code>scripts/regression/nn_los_fast.py</code> - <code>scripts/regression/xgb_los_fast.py</code></p>
</section>
<section id="feature-engineering-deep-dive" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering-deep-dive">2024-11-19 - Feature Engineering Deep Dive</h3>
<p><strong>Key Discovery: Validation vs Kaggle Gap</strong> - Local validation RMSE: ~4.7 - Kaggle score: ~20.8 - This is suspicious! 4.7² ≈ 22, close to 20.8 → <strong>Kaggle may be using MSE, not RMSE</strong></p>
<p><strong>Feature Analysis Completed:</strong></p>
<ol type="1">
<li><strong>Dropped Useless Features:</strong>
<ul>
<li><code>Diff</code> column: correlation with LOS = -0.0012 (zero signal)</li>
<li>Age: correlation = 0.0117 (not useful despite mean age 63.7)</li>
<li>ADMITTIME features (hour, weekend, night): max correlation 0.0205</li>
</ul></li>
<li><strong>Found High-Value Diagnosis Features:</strong>
<ul>
<li>ICD9 codes with high LOS: 51884, 5770, 430, 44101, 0380, 51881, 0389, 431</li>
<li>Diagnosis keywords: PANCREATITIS (8.12 days!), SHOCK (7.85 days), TRANSPLANT, ARREST</li>
<li>Low-LOS keywords: OVERDOSE (2.56), DIABETIC/DKA (2.38)</li>
</ul></li>
<li><strong>Categorical Variable Power (eta-squared):</strong>
<ul>
<li>FIRST_CAREUNIT: η²=0.0186 (most predictive)</li>
<li>ADMISSION_TYPE: η²=0.0105</li>
<li>INSURANCE: η²=0.0074</li>
</ul></li>
<li><strong>Added Interaction Feature:</strong>
<ul>
<li><code>sicu_emergency</code>: SICU + EMERGENCY admission = 4.35 avg LOS</li>
</ul></li>
</ol>
<p><strong>Results:</strong> - Enhanced features improved Kaggle from 21.31 → 20.75 (2.6% improvement) - Validation RMSE improved 4.7551 → 4.6793 (1.6%)</p>
<p><strong>Extreme Value Problem Identified:</strong> - Training LOS ranges 0.06 to 101.74 days - Model predictions cap at ~17-19 days - For LOS 20-50 days (1.9% of data): RMSE = 23.67! - These outliers dominate the error</p>
<p><strong>Approaches Tested:</strong> - ✅ Ensemble (GB+RF+ET): ~20.8 on Kaggle (no improvement) - ❌ Log-transform: Worse on validation (4.67 → 4.80) - All models scoring similarly suggests the issue isn’t the algorithm</p>
<p><strong>Files Created:</strong> - <code>scripts/regression/feature_analysis.py</code> - Main analysis script with all features - <code>scripts/regression/test_age_calculation.py</code> - Verify age calculation - <code>scripts/regression/test_admittime_features.py</code> - Test time features - <code>scripts/regression/explore_all_features.py</code> - Comprehensive feature exploration - <code>scripts/regression/generate_los_submissions_v2.py</code> - Submissions with new features - <code>scripts/regression/generate_los_ensemble.py</code> - GB+RF+ET ensemble - <code>scripts/regression/diagnose_kaggle_gap.py</code> - Investigate val vs Kaggle gap - <code>scripts/regression/generate_los_logtransform.py</code> - Log-transform approach</p>
<hr>
</section>
</section>
<section id="strategy-insights" class="level2">
<h2 class="anchored" data-anchor-id="strategy-insights">🎯 Strategy &amp; Insights</h2>
<section id="classification-strategy" class="level3">
<h3 class="anchored" data-anchor-id="classification-strategy">Classification Strategy</h3>
<ol type="1">
<li><strong>Stick with Gradient Boosting</strong> - Clear winner at 0.727</li>
<li><strong>Simple is better</strong> - Feature engineering didn’t help</li>
<li><strong>Fine-tuning options exist</strong> but current score is competitive</li>
</ol>
</section>
<section id="regression-strategy" class="level3">
<h3 class="anchored" data-anchor-id="regression-strategy">Regression Strategy</h3>
<ol type="1">
<li><strong>Current best:</strong> 20.75 (improved from 21.3)</li>
<li><strong>Gap:</strong> Still ~5 points from 15.7 benchmark</li>
<li><strong>Key Insight:</strong> Validation RMSE² ≈ Kaggle score → might be MSE metric</li>
</ol>
<p><strong>What Worked:</strong> - Diagnosis features (ICD9 codes + text keywords): +2.6% improvement - Dropping useless features (Diff, age, time features)</p>
<p><strong>What Didn’t Work:</strong> - Ensembles: All score ~20.8 (same as single models) - Log-transform: Made things worse - XGBoost: No improvement over GB</p>
<p><strong>Remaining Ideas to Try:</strong> - [ ] Neural Network (since benchmark says “NN demanding”) - [ ] Two-stage model (classify long-stay vs short-stay, then predict) - [ ] Quantile regression (predict median instead of mean) - [ ] More aggressive outlier handling</p>
</section>
<section id="key-technical-decisions" class="level3">
<h3 class="anchored" data-anchor-id="key-technical-decisions">Key Technical Decisions</h3>
<p><strong>Data Preprocessing:</strong> - Median imputation for numerical features - Most frequent imputation for categorical - StandardScaler for numerical features - OneHotEncoder for categorical features - BP outlier cleaning (values below physiological minimums)</p>
<p><strong>Feature Engineering:</strong> - Vital sign ranges (instability indicators) - Critical threshold flags (tachycardia, hypotension, hypoxia) - Shock index (HR/SBP ratio) - Pulse pressure (SBP - DBP) - <strong>Note:</strong> Helped classification validation but hurt test score - use cautiously</p>
<p><strong>Model Selection:</strong> - Classification: Gradient Boosting is clear winner - Regression: Testing multiple approaches (GB baseline, then NN/XGB)</p>
<hr>
</section>
</section>
<section id="project-structure" class="level2">
<h2 class="anchored" data-anchor-id="project-structure">📁 Project Structure</h2>
<pre><code>cml_final/
├── scripts/
│   ├── classification/          # HEF (mortality) prediction
│   │   ├── quickstart_submission.py
│   │   ├── generate_kaggle_submissions.py
│   │   ├── finetune_gb.py
│   │   ├── xgboost_sub.py
│   │   ├── stacking_sub.py
│   │   ├── both_formats.py
│   │   ├── check_setup.py
│   │   └── README.md
│   └── regression/              # LOS (length of stay) prediction
│       ├── los_prep.py
│       ├── quickstart_los.py
│       ├── generate_los_submissions.py
│       ├── nn_los_fast.py
│       ├── xgb_los_fast.py
│       ├── check_setup_los.py
│       └── README.md
├── submissions/
│   ├── classification/          # HEF submission CSVs
│   └── regression/              # LOS submission CSVs
├── data/
│   ├── raw/
│   │   ├── MIMIC III dataset HEF/
│   │   └── MIMIC III dataset LOS/
│   └── output/
├── notebooks/                   # Jupyter notebooks for EDA
└── src/                         # Shared utilities</code></pre>
<hr>
</section>
<section id="environment-setup" class="level2">
<h2 class="anchored" data-anchor-id="environment-setup">🔧 Environment Setup</h2>
<p><strong>Python Packages:</strong> - pandas - numpy - scikit-learn - xgboost - matplotlib - seaborn - jupyter</p>
<p><strong>Installation:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install pandas numpy scikit-learn xgboost matplotlib seaborn jupyter</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
<section id="notes-observations" class="level2">
<h2 class="anchored" data-anchor-id="notes-observations">📝 Notes &amp; Observations</h2>
<section id="what-worked" class="level3">
<h3 class="anchored" data-anchor-id="what-worked">What Worked</h3>
<ul>
<li>✅ Gradient Boosting consistently strong</li>
<li>✅ Clean data preprocessing pipeline</li>
<li>✅ Proper train/validation split with stratification</li>
<li>✅ BP outlier cleaning improved results</li>
</ul>
</section>
<section id="what-didnt-work" class="level3">
<h3 class="anchored" data-anchor-id="what-didnt-work">What Didn’t Work</h3>
<ul>
<li>❌ Feature engineering hurt classification test scores</li>
<li>❌ XGBoost underperformed GB for classification</li>
<li>❌ Ensemble/stacking didn’t beat single GB</li>
<li>❌ Extra Trees significantly worse than RF/GB</li>
<li>❌ Age features for LOS (correlation only 0.0117)</li>
<li>❌ Time features for LOS (weekend, night - max correlation 0.02)</li>
<li>❌ Diff column (correlation -0.0012)</li>
<li>❌ Log-transform for regression (made validation worse)</li>
<li>❌ Ensembles for regression (all score same ~20.8)</li>
</ul>
</section>
<section id="open-questions" class="level3">
<h3 class="anchored" data-anchor-id="open-questions">Open Questions</h3>
<ul>
<li>Is Kaggle using MSE instead of RMSE? (4.7² ≈ 22 ≈ Kaggle 20.8)</li>
<li>Can neural networks close the 5 point gap?</li>
<li>Would a two-stage model help with extreme values?</li>
<li>Are we fundamentally limited by the feature set?</li>
</ul>
<hr>
</section>
</section>
<section id="next-session-todo" class="level2">
<h2 class="anchored" data-anchor-id="next-session-todo">🎯 Next Session TODO</h2>
<p><strong>Immediate:</strong> 1. [ ] Try Neural Network approach (benchmark hint: “NN demanding”) 2. [ ] Consider two-stage model for extreme LOS values 3. [ ] Maybe accept ~20.8 is close to our limit with these features</p>
<p><strong>For Final Submission:</strong> - [ ] Document best approaches for both tasks - [ ] Clean up code and add comments - [ ] Prepare presentation/report - [ ] Archive best submissions</p>
<p><strong>Note:</strong> Professor won’t reveal scoring metric, so we can’t confirm MSE vs RMSE theory</p>
<hr>
</section>
<section id="leaderboard-submissions-history" class="level2">
<h2 class="anchored" data-anchor-id="leaderboard-submissions-history">📊 Leaderboard Submissions History</h2>
<section id="classification-hef" class="level3">
<h3 class="anchored" data-anchor-id="classification-hef">Classification (HEF)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Submission File</th>
<th>Score</th>
<th>Rank</th>
<th>Date</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PROB_submission_gb.csv</td>
<td>0.727226</td>
<td>-</td>
<td>2024-11-19</td>
<td>Best so far</td>
</tr>
<tr class="even">
<td>PROB_submission_ensemble.csv</td>
<td>0.721090</td>
<td>-</td>
<td>2024-11-19</td>
<td></td>
</tr>
<tr class="odd">
<td>PROB_submission_xgboost.csv</td>
<td>0.715164</td>
<td>-</td>
<td>2024-11-19</td>
<td>Underperformed</td>
</tr>
<tr class="even">
<td>PROB_submission_et.csv</td>
<td>0.688217</td>
<td>-</td>
<td>2024-11-19</td>
<td>Worst</td>
</tr>
</tbody>
</table>
</section>
<section id="regression-los" class="level3">
<h3 class="anchored" data-anchor-id="regression-los">Regression (LOS)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Submission File</th>
<th>Score</th>
<th>Rank</th>
<th>Date</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>submission_los_gb_enhanced_v2.csv</td>
<td>20.751931</td>
<td>-</td>
<td>2024-11-19</td>
<td>🏆 Best - diagnosis features</td>
</tr>
<tr class="even">
<td>submission_los_ensemble_weighted.csv</td>
<td>~20.8</td>
<td>-</td>
<td>2024-11-19</td>
<td>GB+RF+ET ensemble</td>
</tr>
<tr class="odd">
<td>submission_los_gb_diagnosis_v2.csv</td>
<td>21.021833</td>
<td>-</td>
<td>2024-11-19</td>
<td>Diagnosis only</td>
</tr>
<tr class="even">
<td>submission_los_xgboost.csv</td>
<td>~21.0</td>
<td>-</td>
<td>2024-11-19</td>
<td>No improvement</td>
</tr>
<tr class="odd">
<td>submission_los_gb.csv</td>
<td>21.309904</td>
<td>-</td>
<td>2024-11-19</td>
<td>Original baseline</td>
</tr>
<tr class="even">
<td>submission_los_ensemble.csv</td>
<td>21.457578</td>
<td>-</td>
<td>2024-11-19</td>
<td></td>
</tr>
<tr class="odd">
<td>submission_los_rf.csv</td>
<td>21.782790</td>
<td>-</td>
<td>2024-11-19</td>
<td></td>
</tr>
<tr class="even">
<td>submission_los_et.csv</td>
<td>22.123555</td>
<td>-</td>
<td>2024-11-19</td>
<td></td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="tips-for-future-me" class="level2">
<h2 class="anchored" data-anchor-id="tips-for-future-me">💡 Tips for Future Me</h2>
<ol type="1">
<li><strong>Always validate locally first</strong> - Don’t waste submissions on untested code</li>
<li><strong>Document parameter changes</strong> - Easy to forget what you tried</li>
<li><strong>Keep old submissions</strong> - Sometimes reverting is the right move</li>
<li><strong>The benchmark is a hint</strong> - “nn demanding” = try neural networks!</li>
<li><strong>Simplicity often wins</strong> - Feature engineering didn’t always help</li>
<li><strong>Check your submission format</strong> - icustay_id + probabilities/values</li>
<li><strong>Test correlations before using features</strong> - Age (0.01) and time (0.02) were useless</li>
<li><strong>Extreme values dominate RMSE</strong> - 1.9% of data (LOS 20-50 days) has RMSE 23.67!</li>
<li><strong>Validation/Kaggle gap can indicate metric mismatch</strong> - 4.7² ≈ 22 ≈ Kaggle 20.8</li>
<li><strong>Ensembles don’t always help</strong> - If models are similar, ensemble won’t improve</li>
</ol>
<hr>
</section>
<section id="resources-references" class="level2">
<h2 class="anchored" data-anchor-id="resources-references">📚 Resources &amp; References</h2>
<ul>
<li><a href="https://mimic.mit.edu/">MIMIC-III Documentation</a></li>
<li><a href="https://scikit-learn.org/">Scikit-learn Documentation</a></li>
<li><a href="https://xgboost.readthedocs.io/">XGBoost Documentation</a></li>
<li>Course materials and lectures</li>
<li>Project PDF requirements</li>
</ul>
<hr>
<p><strong>Last Updated:</strong> 2024-11-19 <strong>Status:</strong> Classification complete (0.727 AUC), Regression improved (20.75 → target 15.7)</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>